### ISSUE TITLE
win10不显示命令，也无任何错误提示

### ISSUE THREAD

**Issue by yfz0574** [zhouhua/obsidian-export-image#10]
直接在社区插件中安装，显示安装成功，但按ctrl+p，却找不到export image等命令，搜索export也无显示，按ctrl+shif+i打开调试控制台，也不显示任何错误，安装时启用时也没显示任何错误信息。

**Comment by yfz0574** [comment]
经群友提示，编辑器切换为阅读视图后菜单命令可见。但发现另一个冲突问题，另开issue讨论。

**Comment by zhouhua** [comment]
Clean up outdated issues. If the problem persists in the new version, please reopen this issue.
