### ISSUE TITLE
导出的图像文件的背景如何控制？

### ISSUE THREAD

**Issue by webrunneronSun** [zhouhua/obsidian-export-image#11]
### 笔记在OB里面的显示效果
![image](https://user-images.githubusercontent.com/119090113/215652175-0c0650a8-5d47-41dc-9c73-f0d1fac76aa1.png)
### 导出后的效果
![image](https://user-images.githubusercontent.com/119090113/215652302-31b34bb5-8972-48ee-8947-85b4e8a92c9b.png)

**Comment by zhouhua** [comment]
背景颜色是读取了markdown 预览区域上层容器的背景颜色，如果做成可配置的，使用起来不太方便。你可以尝试换个主题试试。
