### ISSUE TITLE
跟TimeLines插件冲突至导出图空白。

### ISSUE THREAD

**Issue by yfz0574** [zhouhua/obsidian-export-image#12]
经过仔细排查，发现开启了TimeLines插件，导出图就空白。这是一些相关资料：
![image](https://user-images.githubusercontent.com/11656321/215842770-31f80299-aa0c-400a-9200-b7564fb8bd3c.png)

https://github.com/Darakah/obsidian-timelines
调试控制台排查记录：
![image](https://user-images.githubusercontent.com/11656321/215842964-fb540944-02ec-48f5-97ab-efa97d871827.png)
![image](https://user-images.githubusercontent.com/11656321/215843229-e7f31a45-1049-465d-94f3-f564649cac0f.png)

上面是导出失败的报错信息。
跟踪调试代码发现错误：
![image](https://user-images.githubusercontent.com/11656321/215843415-91d6131a-5b00-4487-a7d9-3e1301eda326.png)

**Comment by yfz0574** [comment]
发现跟copy document as html插件也冲突
![image](https://user-images.githubusercontent.com/11656321/215851496-c1f5ad39-373a-489e-8dc7-bc04195be493.png)
https://github.com/mvdkwast/obsidian-copy-as-html

**Comment by yfz0574** [comment]
测试不够严谨，虽然测试了一小时，但每次测试太急缺少耐心，而OB的响应会有延迟，所以结论不太可靠，仅供参考。
有时间再进行更严谨的测试、排查。

**Comment by zhouhua** [comment]
我现在测试应该不存在冲突问题了
