### ISSUE TITLE
长文导出不完整

### ISSUE THREAD

**Issue by Tera-ravyn** [zhouhua/obsidian-export-image#19]
约1w5字左右，在适合手机阅读的宽度下生成图片无法包含所有文本内容，是限制了图片最大高度吗？

**Comment by zhouhua** [comment]
这个插件没有加什么限制，我刚自己测试了一下，我这边的情况是大约图片高度达到 40000 时，图片就导不出来了，没有复现你说的图片不完整的情况

**Comment by Tera-ravyn** [comment]
感谢，我之前测试不足反馈得也不是很清楚，现在发现应该是：在非pc端全屏状态下文字自然宽度的100%时，高度计算可能有些问题，会导致无法滚动到文本末尾，因此包含的文字不完整。
具体的使用情况是我调出了调试控制台，想要以一个适合手机阅读的宽度进行图片导出。测试过后发现如果是非全屏窗口下使用导出图片，也存在一样的问题。如果能通过操作优化这个问题，请您告知，谢谢！

**Comment by zhouhua** [comment]
文档中都是文字吗，还是有许多图片？由于 obsidian 的内容渲染是做了懒加载的，我没办法直接拿到文档全部内容，只能进行一次滚动，收集全部文档内容，所以可能确实存在不准确的情况。我想想能不能优化一下。

**Comment by zhouhua** [comment]
我刚提交了一个新版本，你看看问题是否有改善

**Comment by zhaoscsc** [comment]
callout样式，有的换错行。
![image](https://github.com/zhouhua/obsidian-export-image/assets/106651497/401129e9-2f1e-4ee5-a49b-ba2cc2df190f)

**Comment by Tera-ravyn** [comment]
辛苦，非常感谢！我的文章中只有纯文字，没有其他内容，测试的情况是在调整窗口大小后首次导出仍然可能有这个问题， 不过保持窗口大小第二遍再次执行导出基本就没有问题了。除此以外还有一点点无伤大雅的小问题，就是yaml区的date属性不知为何具体日期导出后缺失了：
阅读模式：
![原生date属性](https://github.com/zhouhua/obsidian-export-image/assets/70262164/844cef62-2674-4007-b278-b3d346276b26)
导出图片：
![yaml区date属性](https://github.com/zhouhua/obsidian-export-image/assets/70262164/fe30dc96-f3e5-49c0-8802-a8ae462d1260)

**Comment by zhouhua** [comment]
> 约1w5字左右，在适合手机阅读的宽度下生成图片无法包含所有文本内容，是限制了图片最大高度吗？

我刚对插件进行了重构，现在截图的逻辑应该可以确保文字内容的完整，也支持设置图片宽度了，你可以再尝试一下。

**Comment by Tera-ravyn** [comment]
> 我刚对插件进行了重构，现在截图的逻辑应该可以确保文字内容的完整，也支持设置图片宽度了，你可以再尝试一下。

非常好用！感谢！🤗
