### ISSUE TITLE
如果笔记中有外链图片，会引起CORS错误

### ISSUE THREAD

**Issue by cumany** [zhouhua/obsidian-export-image#2]
如图
![image](https://user-images.githubusercontent.com/42957010/197535613-7b696a45-e789-4a34-8f21-20ba7abfe8b6.png)

**Comment by zhouhua** [comment]
这个问题不太好解决，我后续发布一个版本不让这样的图片阻塞插件运行

**Comment by cumany** [comment]
> 这个问题不太好解决，我后续发布一个版本不让这样的图片阻塞插件运行

我记得Obsidian 有个api 可以避免出现cors问题 可以考虑用requestUrl函数试试
https://github.com/obsidianmd/obsidian-api/blob/ff121cd409350d3afe39b08420f468d8aaee925e/obsidian.d.ts#L2745

**Comment by zhouhua** [comment]
确实可行，本地已经跑通了，稍后我会重新发布一下，多谢

**Comment by zhouhua** [comment]
刚发了一个新版本修复这个问题，可以试试看是否正常了。

**Comment by cumany** [comment]
经过测试这个问题已完美解决。
