### ISSUE TITLE
【功能】 导出图片时，隐藏反向链接面板

### ISSUE THREAD

**Issue by yankai19900930** [zhouhua/obsidian-export-image#22]
目前导出图片是将反向链接面板的内容一并导出。该反向面板对于导出图片对外分享带来一定程度的不美观，甚至是隐私外漏：

因此，请求：
①是否可新增一个设置，让使用者选择是否带出该功能？
②或者是否可直接默认不带出该反向面板内容？

![image](https://github.com/zhouhua/obsidian-export-image/assets/135247747/1e00d430-83da-4eca-afb1-ab56632937f0)

**Comment by zhouhua** [comment]
我抽空看一下，我咋感觉改过这个问题呢

**Comment by zhouhua** [comment]
我刚发了 2.0 版本，对截图逻辑进行了重构，顺便也解决了你的问题
