### ISSUE TITLE
[FR] 增加背景图或水印功能

### ISSUE THREAD

**Issue by yankai19900930** [zhouhua/obsidian-export-image#24]
大佬，是否可增加背景抬头这种信息增加？

场景：

希望分享给别人图片时，可以标注来源，做到知识产权说明的作用。

**Comment by zhouhua** [comment]
我也在考虑这个功能，之前担心是我自己憶想的需求，就比较谨慎。不过这几天有点忙，看下周能不能做一下。

**Comment by zhouhua** [comment]
功能已添加，欢迎测试体验！
