### ISSUE TITLE
无法导出拥有Contribution Widget挂件的文档为图片

### ISSUE THREAD

**Issue by miaoziguan** [zhouhua/obsidian-export-image#25]
无法导出拥有Contribution Widget挂件的文档为图片
<img width="736" alt="image" src="https://github.com/zhouhua/obsidian-export-image/assets/115944923/55576f14-8264-41c0-b5fa-cfae69cfab8a">
原页面

<img width="1143" alt="image" src="https://github.com/zhouhua/obsidian-export-image/assets/115944923/d1023074-6592-407d-98fb-3ee1d11408f9">

Contribution Widget介绍：https://mp.weixin.qq.com/s/G3tZajvK4v_rm7ZC1UcCsg

**Comment by zhouhua** [comment]
我不太清楚这个插件中挂件的实现原理，你可以看一下 home.md 这个源文件的内容是啥，导出图片的插件原理是按 obsidian 的规则解析源文件，生成 html，然后生成图片，如果挂件的渲染不是通过在源文件中插入对应的内容，并通过 obsidian 的 api 注入解析逻辑，那么目前是没办法支持的。

**Comment by zhouhua** [comment]
不过也许你可以试一下我这个插件的 1.x.x 版本，在 2.0 之前的实现原理是对阅读模式下已渲染的内容做拷贝截图。

https://github.com/zhouhua/obsidian-export-image/releases/tag/1.0.8

**Comment by zhouhua** [comment]
我修复了，你再试一下

**Comment by miaoziguan** [comment]
万分感谢大佬的付出

Zhou Hua ***@***.***> 于2024年3月25日周一 23:17写道：
