### ISSUE TITLE
Does not update  (android 11)

### ISSUE THREAD

**Issue by merlinuwe** [zhouhua/obsidian-export-image#27]
The latest release of the plugin doesn't update on Android 11.

**Comment by merlinuwe** [comment]
The latest:

![image](https://github.com/zhouhua/obsidian-export-image/assets/4138869/c92a4eaf-9d34-4d55-a239-d694b40d7617)

**Comment by zhouhua** [comment]
Sorry, I didn't understand your question.

**Comment by merlinuwe** [comment]
Ups - wrong picture, sorry.

![image](https://github.com/zhouhua/obsidian-export-image/assets/4138869/375e16ac-c0b0-4cbb-bb3d-d5edf1208038)

**Comment by merlinuwe** [comment]
While updateing, I get an error message in the upper right edge:
![image](https://github.com/zhouhua/obsidian-export-image/assets/4138869/7821ba94-ae9b-49a2-b819-9e97032686fa)

It shows as 2.2.11, but on your webpage is 2.2.10 as the latest available.

This message occures again, if I completely uninstall and try to install again.

When I have uninstalled the plugin, I cannot reinstall it again.

**Comment by zhouhua** [comment]
The short time interval between the releases of 2.2.11 and 2.2.10 explains why there might be display errors in some areas. However, I am unable to resolve the installation error. I believe the installation process for Obsidian plugins involves calling GitHub's openAPI, so installation failures may be related to network connectivity or the stability of the GitHub interface.
