### ISSUE TITLE
Does not built an image (Windows 10)

### ISSUE THREAD

**Issue by merlinuwe** [zhouhua/obsidian-export-image#28]
I get an empty image 600 x 300, regardless if I copy it or save it.

![image](https://github.com/zhouhua/obsidian-export-image/assets/4138869/beaa74cf-a864-4804-b3b9-155ea89e4828)

**Comment by Zhuangkh** [comment]
same issue. no error msg in console

**Comment by ProudBenzene** [comment]
After some troubleshooting, I realized that on my computer, the problem seems to be related to the banners plugin. Just disable the banners plugin to export images normally.

My version of the banners plugin is 2.0.5-beta, so hopefully this information will help the author in fixing the bug.

**Comment by zhouhua** [comment]
@ProudBenzene I also noticed some issues with the banner plugin yesterday, and even the 2.9.9 release yesterday was specifically to fix the problems caused by the banner. However, I only tested it on my Mac. Could you share the error messages you see on your computer?

**Comment by ProudBenzene** [comment]
<img width="1166" alt="iShot_2024-03-28_16 41 14" src="https://github.com/zhouhua/obsidian-export-image/assets/93238080/174500a0-3604-427b-bbe2-b2d9cf6c5842">

<img width="1266" alt="iShot_2024-03-28_16 41 48" src="https://github.com/zhouhua/obsidian-export-image/assets/93238080/39444bbe-a182-41be-88fb-bd5727d7d67e">

<img width="1160" alt="iShot_2024-03-28_16 44 17" src="https://github.com/zhouhua/obsidian-export-image/assets/93238080/d1253a45-8160-4f6e-ba6d-6a88dd7528dd">

When the Banner plugin is on:

1. For a note with a banner inserted (P1), its export screen will only show the banner itself (P2), and the exported image will be the square image from the initial issue.
2. For the notes without the banner inserted (P3), their export interface notes are displayed normally, but the exported image is the square image in the initial issue.

P.S. There is also a small issue not related to banner. It's that when previewing the exported result, you can no longer scale the image freely. Even if the zoom is successful, the image will not stay at the zoomed size, but will quickly bounce back to the original size.

**Comment by merlinuwe** [comment]
I haven't installed banners plugin, 2.2.9 still exports empty images.

**Comment by ProudBenzene** [comment]
Sorry for something I forgot... Finally I succeeded in exporting normal images with the image plugin version 2.2.7. Neither of 2.2.8 or 2.2.9.

On version 2.2.7, regardless of whether the Banner plugin is turned off or not, you can export the image, and it won't export the image without displaying banners that's all. And there will be tips like this: 
<img width="324" alt="image" src="https://github.com/zhouhua/obsidian-export-image/assets/93238080/107f8dda-1ea1-41d7-ad39-2416c16cd689">

**Comment by zhouhua** [comment]
> P.S. There is also a small issue not related to banner. It's that when previewing the exported result, you can no longer scale the image freely. Even if the zoom is successful, the image will not stay at the zoomed size, but will quickly bounce back to the original size.

@ProudBenzene This is because the code has a minimum scaling factor set, so if the preview frame can fully contain the image, further reduction is not allowed.

**Comment by FitzFrobozz** [comment]
Experiencing this today as well. Just prior to the 2.2.9 update I wasn't seeing this issue. (Don't have the Banner plugin installed.)

**Comment by zhaoscsc** [comment]
同样的问题，我也没有安装banner插件，导出失败了。 之前的版本是可以正常使用的。

**Comment by zhouhua** [comment]
I apologize for releasing the recent version without thorough testing, causing inconvenience. I have fixed the issue now.
