### ISSUE TITLE
Support for exporting whole folder contents at once

### ISSUE THREAD

**Issue by sudo-CuriousLad** [zhouhua/obsidian-export-image#33]
Is it possible to implement a feature to export all the files inside a folder to image in one go? Exporting them one by one seems impractical when you have large collections of notes.

**Comment by zhouhua** [comment]
It's possible. Could you discuss why there is such a requirement? If this scenario is realistic and important, I can prioritize implementing this feature.

**Comment by sudo-CuriousLad** [comment]
For example, I am making a collection of notes for my math, physics and chemistry classes. In case i ever want to share them, my classmates would need to use obsidian to view them. It's impractical to make them install an app just to view a couple documents. It's also more convenient to store export images in an archive for future viewing instead of markdown.

Additionally, I am using a tikz obsidian plugin, and that doesn't get rendered outside Obsidian without the plugin. For example: 

Ignore the content of the note, it's currently incomplete
![image](https://github.com/zhouhua/obsidian-export-image/assets/68624376/ddfbb5da-bdce-46eb-ab4b-9f4590d1c2ea)

**Comment by zhouhua** [comment]
I'm pleased to tell you that I've implemented the feature you wanted, and you can download the latest version to try. You can right-click on a folder in the Obsidian file list and click `﻿export all notes to image`.

I think sometimes, when sharing course materials, perhaps a PDF file is better than many image files. Today, I spent a few hours specifically supporting this type of PDF, guessing it might be useful to you.

**Comment by sudo-CuriousLad** [comment]
Thank you so much for this! Also, thing is, I'm not going to sharing the whole thing at once, instead either maintaining an archive or send whichever notes I need to. But the PDF feature will probably come in handy later, so much appreciated regardless.

**Comment by sudo-CuriousLad** [comment]
I just tested the plugin, and I noticed a bug. While the tikz plugin renders in Live Preview mode, it doesn't render anything when exporting the entire folder. I assume this is because of some inter-plugin issues but I'm not sure.
![Intervals](https://github.com/zhouhua/obsidian-export-image/assets/68624376/5cf2be6a-7ed8-4b27-bd5a-59f17b542e64)
![Also Intervals but in Live Preview](https://github.com/zhouhua/obsidian-export-image/assets/68624376/f543d490-ab84-4f62-a18b-9fc331f0c557)

**Comment by sudo-CuriousLad** [comment]
I just realized I should mention which plugin I'm using, sorry.
![Obsidian TikzJax](https://github.com/artisticat1/obsidian-tikzjax)

**Comment by zhouhua** [comment]
Could you share the content of the note that's causing issues, so I can replicate the problem?

**Comment by sudo-CuriousLad** [comment]
Okay, wait one second. I realized that it's not working AT ALL for image export and works for select files with PDF export. 
[Intervals.md](https://github.com/zhouhua/obsidian-export-image/files/14920665/Intervals.md)

**Comment by zhouhua** [comment]
Please try again with the latest version. The issue likely occurs because there isn't enough time given for charts to render completely during batch image export. I've added a bit of delay, which should solve the problem.
