### ISSUE TITLE
Cannot export to jpg

### ISSUE THREAD

**Issue by merlinuwe** [zhouhua/obsidian-export-image#35]
I see an error message, when I try to copy or save an image (standard jpg):

![image](https://github.com/zhouhua/obsidian-export-image/assets/4138869/92e22a25-aa34-423e-8870-9388d7117bb5)

(png and pdf work.)  

Windows 10
Obsidian 1.5.12
Export Image plugin 2.3.3

**Comment by zhouhua** [comment]
Last weekend, I accidentally discovered that in previous versions, the exported JPG images were actually in the wrong format—they were PNGs. So, I spent the weekend fixing this issue, attempting to export images in the true JPG format. From your error message, it appears to be a browser compatibility issue that doesn't allow JPG images to be written to the clipboard.

Is the `save` function working properly for JPG format?

Due to compatibility issues that make the copy to clipboard function unavailable, I might not be able to fix it temporarily. Perhaps the entire copy to clipboard feature could be removed?

**Comment by zhouhua** [comment]
![image](https://github.com/zhouhua/obsidian-export-image/assets/2276598/1782eb48-f440-4f8c-8f4a-a079c8487b51)

Before copying, I added a check to test if the current file format is allowed to be copied.

**Comment by merlinuwe** [comment]
Yes, images can be saved in jpg format.

Currently with release 2.3.3, copying makes png instead of jpg if jpg is set as output.

Your solution is good for the moment. Suggestion: Is it easier for you to export to webp?

**Comment by merlinuwe** [comment]
(I just tried an update, but it failed on Windows 10 and Android; I'll try later again.)

**Comment by zhouhua** [comment]
Oh, sorry, the new version hasn't been released yet. I'll let you know once it's available.

**Comment by zhouhua** [comment]
Could you share your theme configuration with me?

**Comment by zhouhua** [comment]
The two screenshots you sent are a bit hard for me to understand; they look somewhat cluttered. I'm having trouble distinguishing which parts are normal and which parts are problematic.

Perhaps you could take more complete screenshots. If the exported images don't meet your expectations, you could show me a comparison with the style of the note in reading mode.

**Comment by merlinuwe** [comment]
> Could you share your theme configuration with me?

Sure. I use MagicUser, dark, MagicUser Moon. The styles are adapted in style settings plugin. Here is the complete folder with all the adjustments:

[obsidian-style-settings.zip](https://github.com/zhouhua/obsidian-export-image/files/15007848/obsidian-style-settings.zip)

**Comment by merlinuwe** [comment]
> The two screenshots you sent are a bit hard for me to understand; they look somewhat cluttered. I'm having trouble distinguishing which parts are normal and which parts are problematic.
> 
> Perhaps you could take more complete screenshots. If the exported images don't meet your expectations, you could show me a comparison with the style of the note in reading mode.

I made a new TestVault (with only a few plugins) to better isolate the issues. The good thing: Most of the shown issues (screenshots with grey borders around the elements) are gone.

---

At the moment, I see only these issues:

- The lightgrey scrollbars at the right and at the bottom:

![image](https://github.com/zhouhua/obsidian-export-image/assets/4138869/8c874201-b367-43bf-bfce-e4594e3fc9c9)

- A scrollbar in the embedded note:

![image](https://github.com/zhouhua/obsidian-export-image/assets/4138869/dfae5cf7-7a2c-4ed0-8ea6-e716ca3760bf)
 
- The output is cut at the end.

---

This is a screenshot of the 1280px note in view mode:

![UU11C_INF_(anonymisiert)1280view_mode](https://github.com/zhouhua/obsidian-export-image/assets/4138869/60119fd4-e911-481b-834d-af225cee64a1)

This is a screenshot of the 1280px note in edit mode:

![UU11C_INF_(anonymisiert)1280edit_mode](https://github.com/zhouhua/obsidian-export-image/assets/4138869/b1a3908b-2115-484c-b614-bea916713868)

**Comment by zhouhua** [comment]
Could you help by adding this CSS snippet to see if it resolves the issue?

```css
.epxort-image-root,
.export-image-root *,
.export-image-root *::before,
.export-image-root *::after {
  overflow: hidden;
}
```

**Comment by merlinuwe** [comment]
Yes, thanks to your css I see more ...

![image](https://github.com/zhouhua/obsidian-export-image/assets/4138869/ffcbacdd-ceb1-4178-ad51-5420d458b872)

In comparisson the notes end  in view mode:

![image](https://github.com/zhouhua/obsidian-export-image/assets/4138869/6c78f2d1-223b-4957-b64f-388087120001)

The text "20 tasks" are not in the output.

**Comment by zhouhua** [comment]
I'm unable to replicate your issue, making it difficult to debug. Could you share your vault with me?

**Comment by merlinuwe** [comment]
> I'm unable to replicate your issue, making it difficult to debug. Could you share your vault with me?

Sure, but without the google plugin, because of the credentials. 

[2024-04-17-TestVault_export_image.zip](https://github.com/zhouhua/obsidian-export-image/files/15012371/2024-04-17-TestVault_export_image.zip)

**Comment by zhouhua** [comment]
I believe I've resolved the scrollbar issue you encountered. It appears to be a bug in ﻿dom-to-image-more, where during the handling of table styles, the border properties were incorrectly inherited downwards, causing borders to stack and thus occupy more height.

This is the image I exported, and it appears to me to be very close to the reading mode style.

<img src="https://github.com/zhouhua/obsidian-export-image/assets/2276598/b99a7faf-9d28-4370-b701-a3a031f30192" width="100" />

**Comment by merlinuwe** [comment]
I updated to the latest release 2.3.6 and deleted and deactivated the css file, you gave me.

I can confirm, the exported png, png transparent, jpg (640) are fine. 

But the formats webp and pdf (640) are cut off at the end.

I tried up to 2560.

Because of the big amount of data (59,7 MB), I give you this link for downloading:

https://www.swisstransfer.com/d/82316084-3891-4841-88cc-9d983b6992ba

This is the console output:

![image](https://github.com/zhouhua/obsidian-export-image/assets/4138869/b3e7e610-a91b-4985-8a88-a8fe0931601c)

**Comment by merlinuwe** [comment]
Some issues with numbering. This file

[muell - Zifferndarstellung in MagicUser Theme.md](https://github.com/zhouhua/obsidian-export-image/files/15028939/muell.-.Zifferndarstellung.in.MagicUser.Theme.md)

export to pdf works:

[muell - Zifferndarstellung in MagicUser Theme2560.zip](https://github.com/zhouhua/obsidian-export-image/files/15028909/muell.-.Zifferndarstellung.in.MagicUser.Theme2560.zip)

but export to jpg, png, png transparent, webp are not working:

![muell_-_Zifferndarstellung_in_MagicUser_Theme2560](https://github.com/zhouhua/obsidian-export-image/assets/4138869/bc871d35-9684-47e2-9854-a723dde056cd)

![muell_-_Zifferndarstellung_in_MagicUser_Theme_transparent2560](https://github.com/zhouhua/obsidian-export-image/assets/4138869/4d56b8c4-e983-45de-ac85-14ad9bc8dfb0)

![muell_-_Zifferndarstellung_in_MagicUser_Theme2560](https://github.com/zhouhua/obsidian-export-image/assets/4138869/91cab36a-135b-4376-8263-ee1d129ad78d)

**Comment by zhouhua** [comment]
The first issue: Why are WebP images being truncated? This is a limitation of the WebP format, which supports a maximum resolution of 16383 x 16383. For reference: https://developers.google.com/speed/webp/faq?hl=de#what_is_the_maximum_size_a_webp_image_can_be

PDFs face a similar issue, with a maximum size limitation of 200 inches by 200 inches.

The second issue, why the numbers in ordered lists disappear, was a bug introduced while fixing the scrollbar issue. I will fix it shortly. Additionally, the CSS code snippet I previously gave you needs to be removed.

**Comment by zhouhua** [comment]
I believe the issue has been fixed.

**Comment by zhouhua** [comment]
[UU11C_INF_(anonymisiert).png.zip](https://github.com/zhouhua/obsidian-export-image/files/15038612/UU11C_INF_.anonymisiert.png.zip)

This is the image I exported using version 2.3.7, and these two issues you mentioned did not recur, which may be related to differences in operating systems. The disappearing link issue is hard to diagnose; I'll try to get access to a Windows pc to debug it in the next few days. Regarding the first issue with the scrollbar, could you please help by implementing a piece of CSS to test it out:

```css
.epxort-image-root,
.export-image-root .markdown-preview-view {
  overflow: hidden;
}
```

**Comment by merlinuwe** [comment]
Your css gives this result:

The scrollbars are away, again. But the text "20 tracks" is cut ~ 50 % in the half.

![image](https://github.com/zhouhua/obsidian-export-image/assets/4138869/abdad27d-b6e5-41fd-b268-c02ba38282f7)

**Comment by zhouhua** [comment]
Hi @merlinuwe, My investigation suggests that the Dataview component might generate scrollbars when exporting images, which could alter the final image height.

Please help by adding the following CSS code to verify if the issue is resolved (it works on my Windows computer):

```css
.block-language-dataview {
  overflow: hidden !important;
}
```

If it works, I will fix it in the next version.

**Comment by merlinuwe** [comment]
_Without_ your css and release 2.3.7:

![image](https://github.com/zhouhua/obsidian-export-image/assets/4138869/59bfd54f-8752-4efd-8af5-ad4614309148)

Standard Theme:

![image](https://github.com/zhouhua/obsidian-export-image/assets/4138869/5bd30ade-472e-4ad8-8036-31d9e5b7e687)


_With_ your css (as the only one activated) I get (often) this message while copying: "Kopieren fehlgeschlagen". Maybe I pressed the button to fast after opening the export-preview?

---

BTW: 4 days ago you gave me a css snippet with a typo (epxort --> export):

```
.epxort-image-root,
.export-image-root .markdown-preview-view {
  overflow: hidden;
}
```
I tried it with

```
.export-image-root,
.export-image-root .markdown-preview-view {
  overflow: hidden;
}
```
but I see no difference.

---

But I found something new:

The numbers are set to 0:

![image](https://github.com/zhouhua/obsidian-export-image/assets/4138869/a4ad739e-340c-4f67-9a4b-0725256577df)

Background: I use this css to get numbers in tables:

[Tabellennummerierungen.zip](https://github.com/zhouhua/obsidian-export-image/files/15078049/Tabellennummerierungen.zip)

**Comment by zhouhua** [comment]
the numbering problem is fixed.

**Comment by merlinuwe** [comment]
Not in 2.3.7, I see it in the preview, but not in the output-files.

![image](https://github.com/zhouhua/obsidian-export-image/assets/4138869/3a3ff101-bd82-4371-9b30-b9b922be1ffa)

![image](https://github.com/zhouhua/obsidian-export-image/assets/4138869/430aa0a3-cd5e-4c89-9df5-98a6eb536aa3)
