### ISSUE TITLE
Bold & Italic doesn't Render in Blue Topaz Theme

### ISSUE THREAD

**Issue by DoTrONoL** [zhouhua/obsidian-export-image#36]
I suppose this happen because Blue Topaz uses a different text render in _**Bold + Italic**_ (to render that text in gradient color)

I've also tested it in the default PDF export, works fine.

### Settings
![image](https://github.com/zhouhua/obsidian-export-image/assets/71497422/905f3231-668d-4442-b1ca-8e5da86cdb29)

### Preview
![image](https://github.com/zhouhua/obsidian-export-image/assets/71497422/6a249e63-1acb-4ccb-b4a0-031fbd7feac2)

### Export
![image](https://github.com/zhouhua/obsidian-export-image/assets/71497422/7193c405-e0db-46f0-8684-c91f0ec16386)

## Other Theme: _Prism_
_As you can see, it does work fine._
![image](https://github.com/zhouhua/obsidian-export-image/assets/71497422/584dc165-b99d-4dac-b1da-05e00e4322d0)

**Comment by zhouhua** [comment]
I think this bug is the same as the issue discussed [there](https://github.com/1904labs/dom-to-image-more/issues/26). 

I made a fix (6e2dbbb987a99fd5cf6463439b68edc9cb61933d) by referring to the workaround mentioned in that issue.

I'll release the new version later.

**Comment by zhouhua** [comment]
@DoTrONoL I have released a new version; you can try it again.

**Comment by DoTrONoL** [comment]
> @DoTrONoL I have released a new version; you can try it again.

### @zhouhua The result after the update:
![image](https://github.com/zhouhua/obsidian-export-image/assets/71497422/6373bbe8-450c-449f-b762-f05801cfed8c)

**Comment by zhouhua** [comment]
While trying to fix #35, I caused the problem you're experiencing. The solutions to these two issues (#35 & #36) are conflicting, and I need more time to research this further.

**Comment by zhouhua** [comment]
I believe the issue has been fixed.

**Comment by DoTrONoL** [comment]
It was fixed, thanks! Works properly now.
