### ISSUE TITLE
markdown list will not be rendered in the exported picture.

### ISSUE THREAD

**Issue by awaken233** [zhouhua/obsidian-export-image#37]
The result of rendering now

![image](https://github.com/zhouhua/obsidian-export-image/assets/18060521/20d2fd49-fdbd-421a-b1e6-9c9348b16774)

Expected rendering results

![image](https://github.com/zhouhua/obsidian-export-image/assets/18060521/2368335b-befa-48ee-8573-39f8bb6a5a28)

**Comment by zhouhua** [comment]
Could you check the version number of the installed plugin? I should have fixed this issue in version 2.3.7 today.
