### ISSUE TITLE
Error with Border Theme

### ISSUE THREAD

**Issue by ProudBenzene** [zhouhua/obsidian-export-image#38]
作者大大，在使用border主题时，导出图片的预览界面会显示不出图片主体：

<img width="963" alt="image" src="https://github.com/zhouhua/obsidian-export-image/assets/93238080/2998552c-8cb2-4395-8158-20db4d301950">

如果这时候点击导出图片按钮，导出的图片会是一个横着的长方形图片，笔记位于长方形的左边上，长方形的其他部分是空白的。

使用其他主题导出相同的笔记不会出现该情况，不知道是不是一个bug，麻烦作者大大看看👀

**Comment by miaoziguan** [comment]
遇到同样的问题

**Comment by zhouhua** [comment]
我修复这个问题了，可以升级一下插件最新版本试一下

**Comment by ProudBenzene** [comment]
最新版本问题已解决，谢谢作者大大辛苦更新♥️

**Comment by miaoziguan** [comment]
感谢佬，非常完美
