### ISSUE TITLE
插件从2.2.13升级最新版2.3.8之后导出图片时头像不能保存。

### ISSUE THREAD

**Issue by Rayuu** [zhouhua/obsidian-export-image#39]
插件从2.2.13升级最新版2.3.8之后导出图片时头像不能保存。
![image](https://github.com/zhouhua/obsidian-export-image/assets/11494597/76687445-d675-4bb1-9de2-70e3ee6a15b1)

**Comment by zhouhua** [comment]
在修复 #36 时引入这个问题，你更新一下最新的版本再试试
