### ISSUE TITLE
预览模式下运行命令后没有导出图片

### ISSUE THREAD

**Issue by chenmaoran** [zhouhua/obsidian-export-image#4]
Windows，在一个新的库中，只安装这个插件的时候，是可以正常运行的。但是在我平时使用的库中安装之后，运行命令后，页面跳了一下，但是没有弹出选择路径的窗口，无法成功导出图片。

![image](https://user-images.githubusercontent.com/46488675/201913601-2ad30333-8dae-41e5-82f2-37c5eb8c1d97.png)

**Comment by zhouhua** [comment]
能分享一下你的插件列表吗

**Comment by chenmaoran** [comment]
插件列表如下：
![E34E1B88-089E-468D-A5CB-49BFB03319C5](https://user-images.githubusercontent.com/46488675/202082462-2f7ab425-a19e-4a6e-aa5d-c0b4617ab0d8.png)

![D0DF4AD6-B1AA-4361-8FFE-C1A2D6B9F7CF](https://user-images.githubusercontent.com/46488675/202082492-25a6adcf-dd38-4d5e-afff-ddeb6e05c035.png)

我非常喜欢这个插件！昨天试了一下禁用其他插件，重启obsidian以后还是无法导出。谢谢

**Comment by zhouhua** [comment]
[obsidian-export-image.zip](https://github.com/zhouhua/obsidian-export-image/files/10019136/obsidian-export-image.zip)

我还没能查出问题，似乎与其他插件关系不大。我在报错的地方加了一些调试信息的输出，辛苦替换一下插件的代码，重启一下 obsidian，把 console 里的信息截图给我看一下

**Comment by chenmaoran** [comment]
还是报错：
![A2F3B13C-8553-4DB3-A3E6-BF4181D32FC3](https://user-images.githubusercontent.com/46488675/202121602-ae99ee02-0e7f-448e-8a4f-78edf3bf5a9c.png)

**Comment by zhouhua** [comment]
你要输出的文档有什么特别之处吗？有没有图片没有加载出来？

**Comment by chenmaoran** [comment]
没有图片喝其他复杂的格式，纯文本的文档也导不出来。

**Comment by chenmaoran** [comment]
我新建了一个库，把所有的插件和CSS直接复制过去，并且全部启用，还是可以正常到处图片。所以跟插件/CSS没关系。所以真的好难定位问题呀！

**Comment by zhouhua** [comment]
主题一样吗，再排除一下是不是主题的问题

**Comment by chenmaoran** [comment]
我不用第三方主题，一直用原生主题+CSS。我刚才把常用库的配置文件全部复制到新库中，然后就复现了这个问题，一个一个的删除配置文件，貌似好像是workspace.json的问题

**Comment by spiritualgeek** [comment]
> Windows，在一个新的库中，只安装这个插件的时候，是可以正常运行的。但是在我平时使用的库中安装之后，运行命令后，页面跳了一下，但是没有弹出选择路径的窗口，无法成功导出图片。

Same for me and I'm on a mac

**Comment by Ravenclawer** [comment]
我也遇到这个问题了，执行命令后屏幕滚动到页面底部，之后就没有任何反应了。版本0.15.9，windows10

**Comment by zhouhua** [comment]
我无法复现这个问题，需要更多的信息。

I can't reproduce this question, I need more information.

**Comment by dreamstring** [comment]
![image](https://user-images.githubusercontent.com/42427281/209477313-cda31b8d-acf2-4c7f-b53b-5c121ec8d239.png)
I have the same question.

**Comment by zhouhua** [comment]
Clean up outdated issues. If the problem persists in the new version, please reopen this issue.
