### ISSUE TITLE
Images not saving or being copied correctly

### ISSUE THREAD

**Issue by delverdown** [zhouhua/obsidian-export-image#40]
When attempting to save an image, nothing happens whatsoever after clicking the "Save Image" button. There's no indication that it was saved anywhere, and looking around my files shows that it has not been saved.
When copying the image to the clipboard instead, the image pasted elsewhere is a 1-pixel tall horizontal line that has the same width I had defined in the menu.
Additionally, after clicking the "Copy to Clipboard" or "Save Image" buttons, both become locked an unable to be clicked again until I reopen the image menu.

I was going to paste the result of copying the image to clipboard below, but that seems not to work at all here.

**Comment by geeemok** [comment]
same story to me

**Comment by zhouhua** [comment]
Sorry for not responding for such a long time. Could you share the image format you're saving as, the enabled plugins, and the theme you're using? Are there any errors in the console when you try to save the image?

**Comment by geeemok** [comment]
## about image format
it's the same story not matter which format i chose

## theme i,m using
[Blue-Topaz](https://github.com/PKM-er/Blue-Topaz_Obsidian-css)

**Comment by zhouhua** [comment]
I currently don't have an iOS device to test on. Perhaps you could download the vConsole plugin and check if there are any error messages when generating images on iOS? @geeemok

**Comment by geeemok** [comment]
here is the screenshoot. 
the "copy"button at rhight-corner of vConsole seems doesn't work, thats why i upload a img
![微信图片编辑_20240705180430](https://github.com/zhouhua/obsidian-export-image/assets/39703890/44e52623-66ae-4232-b10d-2e13e7c65e67)

**Comment by zhouhua** [comment]
Sorry for the delay, but I believe I've fixed this issue in the latest version.
