### ISSUE TITLE
Feature Request: "Export selected text as image"

### ISSUE THREAD

**Issue by dearbojack** [zhouhua/obsidian-export-image#42]
Thanks for the great plugin, it works like a charm.

Is there a way add an option to "Export selected text as image"?

Best regards.

**Comment by zhouhua** [comment]
I believe this feature is already available. You can select a piece of text, right-click, and see if there is an option in the menu to export the selected content as an image.

**Comment by dearbojack** [comment]
OH, it is! Thanks.
