### ISSUE TITLE
使用 Minimal 主题标题导出为图片时，标题样式无

### ISSUE THREAD

**Issue by FallingSakura** [zhouhua/obsidian-export-image#43]
使用minimal主题时，标题都是有颜色的，但导出时却没有。

**Comment by zhouhua** [comment]
这个不太好修，minimal 主题把弹窗中的标题颜色给重置了，我的插件中图片预览是在弹窗中的，会被影响到。

![image](https://github.com/zhouhua/obsidian-export-image/assets/2276598/d3bfc338-6844-4802-8328-2492416347bb)

一个快速的 workaround 是你引入一段自定义css:

```
body.colorful-headings .modal .markdown-rendered {
  --h1-color: var(--color-red);
  --h2-color: var(--color-orange);
  --h3-color: var(--color-yellow);
  --h4-color: var(--color-green);
  --h5-color: var(--color-blue);
  --h6-color: var(--color-purple);
}
```

**Comment by FallingSakura** [comment]
> 这个不太好修，minimal 主题把弹窗中的标题颜色给重置了，我的插件中图片预览是在弹窗中的，会被影响到。
> 
> ![image](https://private-user-images.githubusercontent.com/2276598/343612726-d3bfc338-6844-4802-8328-2492416347bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTI0NDQsIm5iZiI6MTcxOTQ5MjE0NCwicGF0aCI6Ii8yMjc2NTk4LzM0MzYxMjcyNi1kM2JmYzMzOC02ODQ0LTQ4MDItODMyOC0yNDkyNDE2MzQ3YmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjdUMTI0MjI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzNmZmE0MzBiY2FjOTQ3Y2Y3MzAzNzVhNzNjNGYwMWEzMzVhMmI2ZWUyZjk4MTg4ZTkzMjFjMzBkNjJiZTQwNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tKwwuYGvYdvEYY7m9imwSgTws5ZiB9DIfCulcyW2HU0)
> 
> 一个快速的 workaround 是你引入一段自定义css:
> 
> ```
> body.colorful-headings .modal .markdown-rendered {
>   --h1-color: var(--color-red);
>   --h2-color: var(--color-orange);
>   --h3-color: var(--color-yellow);
>   --h4-color: var(--color-green);
>   --h5-color: var(--color-blue);
>   --h6-color: var(--color-purple);
> }
> ```

哦哦好的
