### ISSUE TITLE
手机端导出时，如果文档内含有图片，则文档内图片会破图无法加载（电脑端正常）

### ISSUE THREAD

**Issue by xupengkun** [zhouhua/obsidian-export-image#44]
问题如标题所示，截图以及录屏如下

平台：手机端
操作系统： 安卓
手机型号： xiaomi 14 pro 
系统版本： Xiaomi HyperOS 1.0.41.0.UNBCNXM
安卓版本： 14
Obsidian版本： v1.5.12(134)
插件版本： v2.3.10

Obsidian里设置的附件保存位置为： “当前文件所在文件夹下指定的子文件夹中”，名字为 “_files”

在手机端尝试修改内部链接类型并重新测试之后也没有作用

望得到回复，感谢

原文档：
![1661720518532_ pic](https://github.com/zhouhua/obsidian-export-image/assets/29838791/7b4245b1-db8c-4764-8e8e-1d94e76bdd97)

导出页面：
![1671720518534_ pic](https://github.com/zhouhua/obsidian-export-image/assets/29838791/9012764a-a977-44c7-a310-189012bbe0a7)

导出结果
![1651720518490_ pic](https://github.com/zhouhua/obsidian-export-image/assets/29838791/2c066246-a228-41c1-a2d0-6c13998222c6)

https://github.com/zhouhua/obsidian-export-image/assets/29838791/54d036c2-c2bf-42d4-825a-6c43f5181e7a

**Comment by zhouhua** [comment]
这个图片能发我一下吗，我不太知道是什么原因，看看图片格式有没有什么问题

**Comment by xupengkun** [comment]
@zhouhua 好的，是随手使用手机拍的一张图，大概3.7m左右，会不会因为太大了？

![1731721009350_ pic_hd](https://github.com/user-attachments/assets/ff6dbedd-4f41-44c7-91cb-c746a95d07bc)

另外使用的其他的obsidian插件有：

<img width="873" alt="image" src="https://github.com/user-attachments/assets/9e7ac4be-13bc-4ffe-b1fd-261ab79d2992">

感谢作者付出以及回复，希望不吝赐教🫰

**Comment by ECSWC** [comment]
@xupengkun 我今天也遇到了这个问题，我发现通banners插件“Add/Change banner with local image”后，问题可解决

**Comment by xupengkun** [comment]
> @xupengkun 我今天也遇到了这个问题，我发现通banners插件“Add/Change banner with local image”后，问题可解决

抱歉我没有用到这个组件，可能是因为这个组件修改了什么设置导致该插件能够运行正常吧，期待作者能够及时更新了

**Comment by benyichan** [comment]
请问移动端的问题解决了吗？
