### ISSUE TITLE
剪切板/导出的图片与预览不一致：预览一行，额外文案总是会显示为两行

### ISSUE THREAD

**Issue by WongYuetYee** [zhouhua/obsidian-export-image#45]
RT
由于单位规定原因无法上传图片，希望作者能帮忙看看，谢谢！！
平台：Windows10
Obsidian版本：v1.6.5
插件版本：2.3.10

**Comment by zhouhua** [comment]
有没有更多一点的信息，比如你所使用的主题，有没有引入什么自定义的 css。方便帮忙测试一下额外文案输入别的内容的效果吗，比如多短的文案才不会换行。还有，有没有缩放过界面，可以试着按下 ctrl + 0 恢复默认缩放百分比。

**Comment by worxift** [comment]
尊敬的开发者，我在 Mac 同样也遇到了这个问题，我的 Obsidian 版本 v1.7.7

![CleanShot 2024-11-28 at 17 26 41](https://github.com/user-attachments/assets/86a9a701-d4e7-4040-9279-e1977c61ceb9)

我是在 appinn 找到推荐您的插件：https://meta.appinn.net/t/topic/63557/4

这个插件解决了我在小红书发精致长图的问题！

请给我支付二维码，我请您喝一杯咖啡！谢谢！

我使用的主题：Material Gruvbox

<img width="733" alt="image" src="https://github.com/user-attachments/assets/0e9a9ec5-444e-4756-aa05-eaa206a54294">

**Comment by zhouhua** [comment]
由于我一直没能复现这个问题，能否帮忙添加一段自定义 css （设置->外观->css代码片断）看问题是否能修复：

```css
.export-image-root .user-info-remark {
  white-space: nowrap;
}
```

感谢

**Comment by worxift** [comment]
代码片段完美的解决了问题！

发到小红书上效果也不错！

请开发者提供一个二维码，请您喝咖啡哈！
https://www.xiaohongshu.com/explore/67491dcc000000000201b059?channelType=web_engagement_notification_page&channelTabId=likes&xsec_token=LBBEN8Q64gn6QRmjk-M9PPwxkk8LKKkYTc0Nzl-32k-Y4=&xsec_source=pc_notice

我是一位心理咨询师，通过小红书推广咨询服务。小红书有一个缺点，就是不支持长图，因此，我生成长图后，再使用在线工具：https://pinetools.com/split-image 分割成多张图片。期待开发者在未来也能支持图片分割。

![Image](https://book.lizaib.com/u/cleanshot-2024-11-29-at-09-39-41-c1Mrt3.gif)

https://book.lizaib.com/u/cleanshot-2024-11-29-at-09-39-41-c1Mrt3.gif

**Comment by worxift** [comment]
必须的！

**Comment by zhouhua** [comment]
我更新了新版本，加入了这个补丁

**Comment by worxift** [comment]
感谢您的工作！支持！

**Comment by zhouhua** [comment]
@worxift，我最近的版本中增加了长图分割的功能

<img width="512" alt="image" src="https://github.com/user-attachments/assets/cd067ef3-a557-423a-84db-8d08ed056e9c" />
