### ISSUE TITLE
Question: Export graph as image

### ISSUE THREAD

**Issue by merlinuwe** [zhouhua/obsidian-export-image#46]
Do you see a chance in enhancing your plugin to export the graph, too?

![image](https://github.com/user-attachments/assets/6078ade5-1026-4949-a6d4-c1262cab9040)

(Or do you know, where the graph is saved?)

**Comment by zhouhua** [comment]
I believe this image is rendered in real-time by Obsidian, so it might not be found in the vault. Perhaps you can directly try this feature:

**Comment by zhouhua** [comment]
I believe this image is rendered in real-time by Obsidian, so it might not be found in the vault. Perhaps you can directly try this feature:

![image](https://github.com/user-attachments/assets/c87ea3b5-53f7-4368-b6bd-ed3612723c7e)
