### ISSUE TITLE
Abnormal display of line spacing between Callout and list

### ISSUE THREAD

**Issue by oceanst1** [zhouhua/obsidian-export-image#48]
After the markdown document is exported as a picture, the Callout will increase a lot compared with the line spacing between lists in edit mode, and this situation will also appear in preview mode or canvas. Excuse me, is there any way to make the exported picture display more similar to the editing mode?
![canva2](https://github.com/user-attachments/assets/c59ac5f6-1434-4757-9f17-1f00a2d525d3)
![canvas1](https://github.com/user-attachments/assets/bdf769b3-3c9b-456a-bda1-cd9b6329515e)
![Edit mode1](https://github.com/user-attachments/assets/5f8e2520-218c-481b-868c-fd62c51e8782)
![Edit mode2](https://github.com/user-attachments/assets/506b87b6-fbb2-4e9f-9f36-ef1f583e14ed)
![Export picture 1 ](https://github.com/user-attachments/assets/e57270c0-e257-48bc-9aa5-f6afbfd01ec8)
![Export picture 2](https://github.com/user-attachments/assets/98361265-56ea-4566-af42-1ac9caf0d3dc)

**Comment by zhouhua** [comment]
When exporting images, I strive to make the image effects as similar to the preview mode as possible, rather than the reading mode. What theme are you using? Perhaps you can resolve your issue by adding some custom CSS.
