### ISSUE TITLE
字体更换请求

### ISSUE THREAD

**Issue by AvalerM** [zhouhua/obsidian-export-image#50]
如何将导出图片的字体更换为其他字体？

**Comment by zhouhua** [comment]
我没有打算在插件里做定制字体的功能，比较简单的方式是直接修改 obsidian 的字体设置就可以了。如果有更精细的字体控制需求，也可以借助自定义 css 实现。

**Comment by AvalerM** [comment]
感谢大佬的回复！
关于您给出的解决方案我曾尝试过第一种！
修改obsidian的字体设置：如果是和我理解的一样是"外观"中的界面、正文和代码字体，已经全部换成目标字体，但导出字体仍为默认字体。不知道该方法的失败与ios移动端是否有关。
第二种方法我想请问无基础情况下，您推荐搜索什么相关教程/关键词呢？
再次感谢您的回复，祝您工作顺利――

/From AM.
________________________________
发件人: Zhou Hua ***@***.***>
发送时间: 星期五, 八月 9, 2024 2:03 下午
收件人: zhouhua/obsidian-export-image ***@***.***>
抄送: AvalerM ***@***.***>; Author ***@***.***>
主题: Re: [zhouhua/obsidian-export-image] 字体更换请求 (Issue #50)


我没有打算在插件里做定制字体的功能，比较简单的方式是直接修改 obsidian 的字体设置就可以了。如果有更精细的字体控制需求，也可以借助自定义 css 实现。

―

**Comment by AvalerM** [comment]
Re：
感谢大佬提供的建议，我换到安卓移动端obsidian更改字体导出成功了，应该是ios移动端的问题，正在寻找其他解决方式！
另：想请问大佬推荐哪方面的css教程可精确地调整字体？谢谢大佬！


 Android 版 Outlook<https://aka.ms/AAb9ysg> 魉
________________________________
