### ISSUE TITLE
ios移动端无法使用自定义字体导出

### ISSUE THREAD

**Issue by AvalerM** [zhouhua/obsidian-export-image#51]
如题，附图，在正文、预览界面显示正常，导出后变成默认字体，求大佬解决![mmexport1723316004323](https://github.com/user-attachments/assets/91bf9eb9-f7de-4fe6-899f-c91f6432b692)
![mmexport1723316005780](https://github.com/user-attachments/assets/59021e36-6eb0-4e95-a08d-fa7199f7f6df)

**Comment by DBaob** [comment]
加一，我也遇到了这种情况，求大佬解决

**Comment by zhouhua** [comment]
我刚发布了一个新版本，麻烦帮忙看看问题是否已经解决

**Comment by AvalerM** [comment]
您好，很抱歉现在才测试。ios端仍旧是：预览为自定义字体，但输出图片为ios默认字体。
谢谢您的答复。

/From AM.
________________________________
发件人: Zhou Hua ***@***.***>
发送时间: Friday, December 6, 2024 5:54:05 PM
收件人: zhouhua/obsidian-export-image ***@***.***>
抄送: AvalerM ***@***.***>; Author ***@***.***>
主题: Re: [zhouhua/obsidian-export-image] ios移动端无法使用自定义字体导出 (Issue #51)


我刚发布了一个新版本，麻烦帮忙看看问题是否已经解决

―
