### ISSUE TITLE
插入本地图片的md文档无法正确显示

### ISSUE THREAD

**Issue by benyichan** [zhouhua/obsidian-export-image#55]
您好 插件在预览时是可以完整看到图片的，但是在导出时文档中的图片就不能显示了，请问是什么原因导致的？

我主要用移动端，设备是魅族21

如图：![凉拌菜-凉拌黄瓜、蒸蟹.png](https://github.com/user-attachments/assets/71769f15-53e6-4e93-84ec-65ca65074dd7)

感谢回复(^🙏^)

**Comment by zhouhua** [comment]
我刚发了一个新版本修复了这个问题

**Comment by benyichan** [comment]
Best RegardsFrom benyi
