### ISSUE TITLE
[Bug] Copy as Image Not Working on iOS

### ISSUE THREAD

**Issue by FelipeRearden** [zhouhua/obsidian-export-image#6]
Hello @zhouhua !!!!

First of all, thank you very much for this plugin. I have been looking for an export plugin for a long time.

When I use the command <kbd>Copy as Image</kbd> on iPadOS, unfortunately its not working :(

I noted 2 things:

ℹ️ The `Copied!` notification is not visible 

ℹ️ The console is showing negative value for `scollHeight: -16 `

📹 On the right is the Note <-> On the Left is the Console 

https://user-images.githubusercontent.com/85180696/202857998-57eff892-ae37-4817-a1b1-35e98e6b1f8c.MOV

---

I hope you could find a solution for iOS 🙏🙏🙏

Thank you very much for reading this 

Have a great day !

**Comment by zhouhua** [comment]
I didn't test it on ipad yet. I'll try to fix the bug in this week.

**Comment by FelipeRearden** [comment]
> I didn't test it on ipad yet. I'll try to fix the bug in this week.

Thank you very much for your reply @zhouhua !

I hope you find a solution 🙏🙏🙏

**Comment by zhouhua** [comment]
Clean up outdated issues. If the problem persists in the new version, please reopen this issue.
