### ISSUE TITLE
文件如果含有外链图片，导出的图片中外链图片缺失

### ISSUE THREAD

**Issue by hellspector** [zhouhua/obsidian-export-image#60]
将文件导出图片时，预览的时候还是正常的，但是一旦clipboard 或者保存后，保存的图片中的外链图片就变成空白了。

ios系统，插件最新版本，Obsidian.1.6.7

好像有人提过issues 说本地图片也无法显示，都是同样的结果。

手机端都无法导出图片。

**Comment by hzlijc** [comment]
我也遇到同样的问题，本地图片。

**Comment by calmwaves111** [comment]
同样的问题

**Comment by zhouhua** [comment]
我更新了新版本，尝试解决移动端图片问题，我手头只有安卓手机，已经测试通过了，麻烦帮忙看看 ios 是否也解决问题。

**Comment by calmwaves111** [comment]
> 我更新了新版本，尝试解决移动端图片问题，我手头只有安卓手机，已经测试通过了，麻烦帮忙看看 ios 是否也解决问题。

我这里是安卓12，已经没问题了，感谢作者大大修复
