### ISSUE TITLE
"cssclass" of a note does not affect the image

### ISSUE THREAD

**Issue by Xenareee** [zhouhua/obsidian-export-image#61]
First of all, thank you for the plugin! It's easy to use and very useful.

I use the `cssclass` frontmatter field a lot on my notes to assign custom colors, and noticed that the _css classes do not affect the image._

### Steps to reproduce:
1. create a css snippet that affects some element of a note if it's of a certain class and enable it in the vault. (Example:)
```css
.test-class b, .test-class strong, .test-class .cm-strong {
    color: red !important;
}
````
2. Add the class to a note via frontmatter. (Example:)
```yaml
---
cssclass: test-class
---
```
3. Write something in the note that will be affected by the snippet. (Example: `**this text should be red**`)
4. Open the `"Export to image"` modal. The style is not applied here.

![image](https://github.com/user-attachments/assets/81d60224-0927-44af-ac0b-e9dfe6ab1c7e)
![image](https://github.com/user-attachments/assets/8517728e-a9cb-4ff5-9a59-356e4d3d094b)

### Note
The classes are simply not added to the image preview `export-image-root` container element.

ce43aa367a1a73e53ea1fa562a5c43e29402a7f8 might be responsible for this. If ignoring the css classes is intentional, could a toggle be added in the plugin settings instead? I'd be happy to try and do the change myself if there's no problem with adding such a toggle, or making the classes work by default.

**Comment by zhouhua** [comment]
Oh, I think you should use `cssclasses`.

> https://obsidian.md/changelog/2023-07-26-desktop-v1.4.0/

![image](https://github.com/user-attachments/assets/edfe591a-d84e-4585-b358-5c0aa595ca24)

**Comment by Xenareee** [comment]
I was not aware `cssclass` is deprecated in favor of `cssclasses`, so thank you for the information.

However, if `cssclasses` is used on a note, the image export window fails to open fully with this error:
```
Uncaught TypeError: ((intermediate value) || []).join is not a function
    at eval (plugin:obsidian-export-image:49138:93)
    at Nh (plugin:obsidian-export-image:5095:12)
    at Yi (plugin:obsidian-export-image:5719:12)
    at Vk (plugin:obsidian-export-image:8393:100)
    at Uk (plugin:obsidian-export-image:7976:16)
    at Tk (plugin:obsidian-export-image:7969:9)
    at Ik (plugin:obsidian-export-image:7952:11)
    at Nk (plugin:obsidian-export-image:7668:12)
    at Gk (plugin:obsidian-export-image:7599:62)
    at J2 (plugin:obsidian-export-image:1685:22)
    at Immediate.R2 (plugin:obsidian-export-image:1719:16)
    at process.processImmediate (node:internal/timers:476:21)
```

![image](https://github.com/user-attachments/assets/f2d51c9d-6e10-443b-8e21-6e1153df0bf9)
