### ISSUE TITLE
Two Bugs about Metadata Exporting

### ISSUE THREAD

**Issue by ProudBenzene** [zhouhua/obsidian-export-image#63]
Hello, it's been a long time, your plugin has been a great productivity booster for me, but as I've recently renewed my requirement for metadata export, I've realized that there are two small issues with your plugin for metadata export:

<img width="558" alt="iShot_2024-10-18_23 19 37" src="https://github.com/user-attachments/assets/17bdb62c-190c-4ddf-ac7f-bf2ec17a52f9"><img width="595" alt="iShot_2024-10-18_23 19 55" src="https://github.com/user-attachments/assets/7e13acba-9d41-438c-b750-5a997129b20f">

The first issue, as shown above, is that when the metadata category is "_List_", if the attribute name contains uppercase letters, it will cause the list to appear disorganized in the exported results.

![](https://figure-bed123.oss-cn-beijing.aliyuncs.com/iShot_2024-10-18_23.22.26.png)

Then there is the second problem, as shown above, the `aliases` attribute can't be displayed in the exported image, I think it might be related to this "_list_" reason as well.

I hope you can fix this bug, and thanks again for boosting my productivity and maintaining such a great Obsidian plugin!

**Comment by zhouhua** [comment]
第一个问题是因为 obsidian 保存 metadata 时，都是把属性名按小写处理的，我之前没有注意到这个问题，所以遇到大写的属性名时，就会查不到属性的 type，最后当成普通文本处理了，这个已经修复了。

第二个问题是我故意把 aliases 给屏蔽了（这个做法是错误的），原因是 cssclasses、aliases、tags 几个属性比较特殊，在 obsidian 里有特殊作用，我在处理 cssclasses 时，把 aliases 也一起屏蔽了。这个问题也已经修复了。
