### ISSUE TITLE
Images aren't exported correctly on Android

### ISSUE THREAD

**Issue by dmitryguskv** [zhouhua/obsidian-export-image#66]
I'm sorry if the question is already solved, I haven't been able to find it among this half-chinese branch

When I'm trying to export my note with images in it, it shows me something like this. What should I do?
![Screenshot_20241205_220413](https://github.com/user-attachments/assets/aaa8337b-2430-4c5d-9b93-506e23032131)

**Comment by zhouhua** [comment]
This issue hasn't been resolved yet. I haven't spent much time on adapting for mobile devices before, and I apologize for that.

**Comment by zhouhua** [comment]
I just released a new version, and this issue has been resolved based on my testing on my Android phone.

**Comment by dmitryguskv** [comment]
Yes, it's working now, thank you soooo much!!!!
