### ISSUE TITLE
在macOS下导出图片失败

### ISSUE THREAD

**Issue by 0xHJK** [zhouhua/obsidian-export-image#7]
Obsidian Version 1.0.3 (Installer 1.0.3)

<img width="552" alt="image" src="https://user-images.githubusercontent.com/8033563/206644414-e0fc41e1-b7f5-4eb0-aa1c-e10f8a693f69.png">

**Comment by urania1012** [comment]
same issue

**Comment by zhouhua** [comment]
Clean up outdated issues. If the problem persists in the new version, please reopen this issue.
