### ISSUE TITLE
很有用的插件，请问是否考虑让水印文字支持日期变量？

### ISSUE THREAD

**Issue by tyf2018** [zhouhua/obsidian-export-image#73]
很有用的插件，请问是否考虑让水印文字支持日期变量？

**Comment by zhouhua** [comment]
你有期望的实现方式吗？我感觉做了这个功能后很难向别人讲明白要怎么用。

**Comment by tyf2018** [comment]
> 你有期望的实现方式吗？

就比如用{{yyyy-MMMM-dd}}或{{date}}表示当天日期，用户一看就明白

**Comment by zhouhua** [comment]
我提供给你一个别的方式绕过这个问题，这个周末我开发了一个工具生成当前日期的图片：https://date-image-generator.vercel.app/，通过这个工具你可以得到包含当前日期图片的 url（这是动态的图片，每天打开都是当天的日期期），以此图片为截图添加水印，以下是效果图，你可以参考一下：

<img width="1321" alt="image" src="https://github.com/user-attachments/assets/701e22d0-c2af-46ae-bb27-582cd9943168" />

**Comment by tyf2018** [comment]
厉害。新问题来了，上传图片似乎只能上传本地图片，没找到填在线图片URL的输入栏
![image](https://github.com/user-attachments/assets/ded15545-9d47-42ca-aac4-0d6632b2f5f5)

**Comment by zhouhua** [comment]
设置页面 url 输入看来是我漏加了，我稍晚点加一下

**Comment by zhouhua** [comment]
我更新了一个版本，可以在设置页设置水印url
