### ISSUE TITLE
导出时能否支持自定义 CSS 片段？

### ISSUE THREAD

**Issue by yuanfoudev** [zhouhua/obsidian-export-image#76]
导出图片的使用场景往往是分享场景，而主题开发难度比较大，如果能支持自定义 CSS 片段，则非常方便容易上手。

**Comment by zhouhua** [comment]
你可以直接添加全局的 css 代码片段，在导出图片的正文部分，与阅读模式的样式是一样的。我想我可以在文档里补充一下导出图片内容的 dom 结构，方便有能力的朋友自己编辑 css。

**Comment by yuanfoudev** [comment]
> 你可以直接添加全局的 css 代码片段，在导出图片的正文部分，与阅读模式的样式是一样的。我想我可以在文档里补充一下导出图片内容的 dom 结构，方便有能力的朋友自己编辑 css。

不不不，您可能误会我的意思了，Obsdian 本身自带的全局 CSS 代码片段我不想去动他，我的意思是能否在导出设置的界面上再设置一层 CSS 片段读取覆盖，最后的预览是单独的效果。
![CleanShot-2024-12-19-10 24 17](https://github.com/user-attachments/assets/b8b3367c-3557-43d2-9a96-e92f8ece004f)

**Comment by zhouhua** [comment]
![image](https://github.com/user-attachments/assets/94df9ef7-c411-4c25-863e-c26d86386f29)
我说的是这个功能， obsidian 本身可以很方便地引入自定义 css，只需要在你的 css 中加上导出图片时特定的 class 就可以只影响导出图片的场景

**Comment by yuanfoudev** [comment]
“只需要在你的 css 中加上导出图片时特定的 class 就可以只影响导出图片的场景”

那么导出图片时特定的 class 是什么呢？

**Comment by zhouhua** [comment]
![image](https://github.com/user-attachments/assets/162967ca-baa4-4167-8903-bd95c052a0f1)

我刚更新了一下 readme。

**Comment by yuanfoudev** [comment]
这个问题我改了好几遍，解决了。
