### ISSUE TITLE
可以考虑为选中文字导出图片做一个命令吗？

### ISSUE THREAD

**Issue by yuanfoudev** [zhouhua/obsidian-export-image#77]
目前快捷键只能导出全部文件内容为图片

**Comment by zhouhua** [comment]
不过如果你对选中文本导出这个操作有更高的效率要求，我有一个建议，可以试试我的另一个插件：[popkit](https://github.com/zhouhua/obsidian-popkit)，这个插件是可以在选中内容时弹出快捷菜单，然后配置一下导出图片的命令：

![image](https://github.com/user-attachments/assets/e5eacea5-f7ad-4f3c-bef2-d82f9a7bb2eb)

**Comment by yuanfoudev** [comment]
非常感谢你的回复，因为目前我采用的是 popclip 方案，所以打算曲线救国，在 ob 设置好命令快捷键，然后通过 popclip 自制插件去启动这个命令。

1、我是一个 pm，经常对内容导出有需求，在我尝试大量的分享卡片、pdf 产品后，才真正认清楚导出场景的核心诉求：

- 短文本的载体最好是卡片图片，比如各种金句，支持背景图片的这种。
- 长文本如一整篇文章、教程、用户手册，那还是 pdf 或者 md 形式的文本载体较好。

2、至于效率问题，我是朴素地认为分享命令越便捷，则分享的成功率则越高，当前这个插件非常完美，但是每次都弹出分享设置框其实是有一点的阻塞的。

3、对于“选中文本导出”，我完整的想法是：能通过选中文本快速导出为图片，并且快速粘贴到剪贴板，不需要样式确认（样式确认可以放在插件设置内完成）。

**Comment by zhouhua** [comment]
我也有想法认真研究开发一个分享体验好的产品，但载体不是 ob，希望有机会能与你深入探讨。我认为分享环节是内容价值实现的重要环节，而目前的内容生产工具都忽视这个环节。

至于 ob 插件，我可以支持跳过设置的步骤。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月20日 09:17 |
| 收件人 | ***@***.***> |
| 抄送至 | Zhou ***@***.***>***@***.***> |
| 主题 | Re: [zhouhua/obsidian-export-image] 可以考虑为选中文字导出图片做一个命令吗？ (Issue #77) |

非常感谢你的回复，因为目前我采用的是 popclip 方案，所以打算曲线救国，在 ob 设置好命令快捷键，然后通过 popclip 自制插件去启动这个命令。

1、我是一个 pm，经常对内容导出有需求，在我尝试大量的分享卡片、pdf 产品后，才真正认清楚导出场景的核心诉求：

短文本的载体最好是卡片图片，比如各种金句，支持背景图片的这种。
长文本如一整篇文章、教程、用户手册，那还是 pdf 或者 md 形式的文本载体较好。

2、至于效率问题，我是朴素地认为分享命令越便捷，则分享的成功率则越高，当前这个插件非常完美，但是每次都弹出分享设置框其实是有一点的阻塞的。

3、对于“选中文本导出”，我完整的想法是：能通过选中文本快速导出为图片，并且快速粘贴到剪贴板，不需要样式确认（样式确认可以放在插件设置内完成）。

**Comment by yuanfoudev** [comment]
“
我也有想法认真研究开发一个分享体验好的产品，但载体不是 ob，希望有机会能与你深入探讨。我认为分享环节是内容价值实现的重要环节，而目前的内容生产工具都忽视这个环节。

至于 ob 插件，我可以支持跳过设置的步骤。
”

欢迎交流，我的微信是： foufoufm

我和你的看法一致，目前大多数内容生产工具专注点都忽略了分享环节，有任何关于新产品的想法可以随时找我交流。

**Comment by zhouhua** [comment]
![image](https://github.com/user-attachments/assets/0d0a000d-b00e-4dd2-9d17-433d51c84915)

我增加了一个配置项，开启后导出选中文本为图片时会跳过设置页面。 @yuanfoudev

**Comment by yuanfoudev** [comment]
感谢，已彻底闭环
