### ISSUE TITLE
安卓无法导出图片

### ISSUE THREAD

**Issue by Clevalend-Z** [zhouhua/obsidian-export-image#8]
你好！我非常喜欢这个插件。它在windows上运行完美，但是在手机上不能使用。
当我在预览状态下用命令面板使用复制或导出时，我可以看到页面有滚动，但是之后什么都没有发生。
尝试过关闭其他插件和重启ob。版本是移动端1.4.1。
非常感谢。

**Comment by wangweitung** [comment]
确实如此，我的也无法截屏
