### ISSUE TITLE
Image Not Copied or Save; Render Issue

### ISSUE THREAD

**Issue by edwin-laman7** [zhouhua/obsidian-export-image#9]
Hi Zhou,

Thank you for making this plugin. It was working fine on my office desktop, but it doesn't work on MacOS Ventura 13.0.

I tried to view using Inspect Tool and figured out the issue;

"plugin:obsidian-export-image:248 Uncaught (in promise) TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLCanvasElement or HTMLImageElement or HTMLVideoElement or ImageBitmap or OffscreenCanvas or SVGImageElement or VideoFrame)'.
    at eval (plugin:obsidian-export-image:248:33)
    at async eval (plugin:obsidian-export-image:859:28)"

I am guessing it's either of the followings;

1 - No proper rights were given to Obsidian (I have enabled screen recording)
2 - Rendering incorrect

Appreciate your help on this.

**Comment by merlinuwe** [comment]
Same here on Windows 10.
